packages:
  - 'adyen'
  - 'aws'
  - 'commons'
  - 'gohighlevel'
  - 'logging'
  - 'lucia-adapter-dynamodb'
  - 'middesk'
  - 'qwik-icons'
  - 'qwik-ui'
  - 'usps'
  - '!**/dist/**'
catalog:
  "@aws-sdk/client-bedrock-runtime": "^3.958.0"
  "@aws-sdk/client-dynamodb": "3.958.0"
  "@aws-sdk/client-eventbridge": "3.958.0"
  "@aws-sdk/client-geo-places": "3.958.0"
  "@aws-sdk/client-lambda": "3.958.0"
  "@aws-sdk/client-location": "3.958.0"
  "@aws-sdk/client-s3": "3.958.0"
  "@aws-sdk/client-secrets-manager": "3.958.0"
  "@aws-sdk/client-ses": "3.958.0"
  "@aws-sdk/client-sqs": "3.958.0"
  "@aws-sdk/client-sts": "3.958.0"
  "@aws-sdk/lib-dynamodb": "3.958.0"
  "@aws-sdk/s3-request-presigner": "3.958.0"
  "@aws-sdk/util-dynamodb": "3.958.0"
  "@builder.io/qwik": "1.19.0"
  "@builder.io/qwik-city": "1.19.0"
  "@eslint/js": "^9.39.3"
  "@lucia-auth/adapter-test": "^5.0.2"
  "@tailwindcss/vite": "^4.2.0"
  "@types/aws-lambda": "8.10.160"
  "@types/node": "^24.10.13"
  "daisyui": "^5.5.18"
  "dotenv-cli": "^11.0.0"
  "eslint": "9.39.3"
  "eslint-plugin-qwik": "1.19.0"
  "globals": "17.3.0"
  "ksuid": "3.0.0"
  "lucia": "^3.2.2"
  "nanoid": "^5.1.6"
  "np": "^11.0.2"
  "openapi-typescript": "7.13.0"
  "pino": "^10.3.1"
  "pino-abstract-transport": "^3.0.0"
  "prettier": "3.8.1"
  "prettier-plugin-tailwindcss": "^0.7.1"
  "sonic-boom": "^4.2.1"
  "tailwindcss": "^4.2.0"
  "tailwindcss-animated": "2.0.0"
  "testcontainers": "^11.12.0"
  "typescript": "5.9.3"
  "typescript-eslint": "8.56.0"
  "undici": "*"
  "uuid": "^13.0.0"
  "vite": "7.3.1"
  "vite-tsconfig-paths": "^6.1.1"
  "vitest": "4.0.18"
