packages:
  - 'logging'
  - 'qwik-icons'
  - '!**/dist/**'
catalog:
  "@builder.io/qwik": "1.18.0"
  "@eslint/js": "latest"
  "@types/node": "20.19.0"
  "eslint": "9.32.0"
  "eslint-plugin-qwik": "1.18.0"
  "globals": "16.4.0"
  "np": "^8.0.4"
  "pino": "^9.5.0"
  "pino-abstract-transport": "^2.0.0"
  "prettier": "3.6.2"
  "sonic-boom": "^4.2.0"
  "tslib": "^2.8.1"
  "typescript": "5.4.5"
  "typescript-eslint": "8.38.0"
  "undici": "*"
  "vite": "7.2.6"
  "vite-tsconfig-paths": "^4.2.1"
  "vitest": "4.0.6"
