packages:
  - 'aws'
  - 'commons'
  - 'gohighlevel'
  - 'logging'
  - 'lucia-adapter-dynamodb'
  - 'qwik-icons'
  - 'qwik-ui'
  - '!**/dist/**'
catalog:
  "@aws-sdk/client-bedrock-runtime": "^3.958.0"
  "@aws-sdk/client-dynamodb": "3.958.0"
  "@aws-sdk/client-eventbridge": "3.958.0"
  "@aws-sdk/client-geo-places": "3.958.0"
  "@aws-sdk/client-lambda": "3.958.0"
  "@aws-sdk/client-location": "3.958.0"
  "@aws-sdk/client-s3": "3.958.0"
  "@aws-sdk/client-secrets-manager": "3.958.0"
  "@aws-sdk/client-ses": "3.958.0"
  "@aws-sdk/client-sqs": "3.958.0"
  "@aws-sdk/client-sts": "3.958.0"
  "@aws-sdk/lib-dynamodb": "3.958.0"
  "@aws-sdk/s3-request-presigner": "3.958.0"
  "@aws-sdk/util-dynamodb": "3.958.0"
  "@builder.io/qwik": "1.19.2"
  "@builder.io/qwik-city": "1.19.2"
  "@eslint/js": "^9.39.4"
  "@inlang/cli": "^3.1.9"
  "@inlang/paraglide-js": "^2.16.0"
  "@lucia-auth/adapter-test": "^5.0.2"
  "@tailwindcss/vite": "^4.2.4"
  "@types/aws-lambda": "8.10.161"
  "@types/node": "^24.10.13"
  "daisyui": "^5.5.19"
  "dotenv-cli": "^11.0.0"
  "eslint": "9.39.4"
  "eslint-plugin-qwik": "1.19.2"
  "globals": "17.5.0"
  "ksuid": "3.0.0"
  "libphonenumber-js": "^1.12.41"
  "lucia": "^3.2.2"
  "nanoid": "^5.1.7"
  "np": "^11.1.0"
  "openapi-typescript": "7.13.0"
  "pino": "^10.3.1"
  "pino-abstract-transport": "^3.0.0"
  "prettier": "3.8.3"
  "prettier-plugin-tailwindcss": "^0.7.1"
  "sonic-boom": "^5.0.0"
  "tailwindcss": "^4.2.4"
  "tailwindcss-animated": "2.0.0"
  "testcontainers": "^11.14.0"
  "typescript": "5.9.3"
  "typescript-eslint": "8.59.0"
  "undici": "*"
  "uuid": "^13.0.0"
  "valibot": "^1.3.1"
  "vite": "7.3.5"
  "vite-tsconfig-paths": "^6.1.1"
  "vitest": "4.1.11"
