packages:
  - 'aws'
  - 'commons'
  - 'gohighlevel'
  - 'logging'
  - 'lucia-adapter-dynamodb'
  - 'qwik-icons'
  - 'qwik-ui'
  - '!**/dist/**'
catalog:
  "@aws-sdk/client-dynamodb": "3.958.0"
  "@aws-sdk/client-eventbridge": "3.958.0"
  "@aws-sdk/client-geo-places": "3.958.0"
  "@aws-sdk/client-lambda": "3.958.0"
  "@aws-sdk/client-location": "3.958.0"
  "@aws-sdk/client-s3": "3.958.0"
  "@aws-sdk/client-secrets-manager": "3.958.0"
  "@aws-sdk/client-ses": "3.958.0"
  "@aws-sdk/client-sqs": "3.958.0"
  "@aws-sdk/lib-dynamodb": "3.958.0"
  "@aws-sdk/s3-request-presigner": "3.958.0"
  "@aws-sdk/util-dynamodb": "3.958.0"
  "@builder.io/qwik": "1.18.0"
  "@eslint/js": "latest"
  "@lucia-auth/adapter-test": "^5.0.2"
  "@tailwindcss/vite": "^4.1.17"
  "@types/aws-lambda": "8.10.152"
  "@types/node": "^20.19.0"
  "@types/uuid": "^10.0.0"
  "daisyui": "^5.5.14"
  "dotenv-cli": "^11.0.0"
  "eslint": "9.32.0"
  "eslint-plugin-qwik": "1.18.0"
  "globals": "16.4.0"
  "ksuid": "3.0.0"
  "lucia": "^3.2.2"
  "np": "^8.0.4"
  "openapi-typescript": "7.10.1"
  "pino": "^10.1.0"
  "pino-abstract-transport": "^3.0.0"
  "prettier": "3.8.1"
  "prettier-plugin-tailwindcss": "^0.7.1"
  "sonic-boom": "^4.2.0"
  "tailwindcss": "^4.1.17"
  "testcontainers": "^10.28.0"
  "tslib": "^2.8.1"
  "typescript": "5.4.5"
  "typescript-eslint": "8.38.0"
  "undici": "*"
  "uuid": "^11.0.5"
  "vite": "7.2.6"
  "vite-tsconfig-paths": "^4.2.1"
  "vitest": "4.0.6"
